apiVersion: v1
kind: Pod
metadata:
  name: thorenv
spec:
  containers:
  - name: pub
    image: thorenv/dev-amr:sllidar
    command: ["/bin/bash", "-c", "source /opt/ros/humble/install/setup.bash && source ~/sllidar_ros2/install/setup.bash && ros2 launch sllidar_ros2 sllidar_s2e_launch.py udp_ip:=192.168.11.4"]
  - name: sub
    image: thorenv/dev-amr:sllidar
    command: ["/bin/bash", "-c", "source /opt/ros/humble/install/setup.bash && ros2 topic hz /scan"]
